### ISSUE TITLE
CP950 Invalid Character

### ISSUE THREAD

**Issue by reidlai** [lumapps/lumX#264] opened 2015-05-14 06:15 UTC
When I import bower_components/lumx/dist/scss/_lumx.scss and compile, I got the following error

Running "sass:compile" (sass) task
Error: Invalid CP950 character "\xE2"
        on line 33 of bower_components/lumx/dist/scss/tools/_responsive.scss
        from line 13 of bower_components/lumx/dist/scss/_lumx.scss
        from line 2 of stylesheets/styles.scss
  Use --trace for backtrace.

After tracing the problem, I found the problem was the single quote at line 23 and 31.  After replace those "'", problem was solved.

**Comment by jmijmi** [comment] 2015-05-14 06:18
+1

**Comment by malexandre** [comment] 2015-05-18 10:00
Hi!

Where exactly did you change this? In the comments? We don't have any problem when working in an utf-8 environment. I know that when I'm working on Windows, I can't compile the SCSS of LumX (and almost any project) because of the default encoding of the console. I need to type `chcp 1252`.

Are you on Windows too? If yes, we won't fix that. It's not a bug from LumX, but a bug between Windows & Ruby. If you're not on Windows, I'll investigate this.

**Comment by matmkian** [comment] 2016-05-12 16:03
In the last version, we've reworked and fixed a lot of things. If this issue is still happening, please re-open the issue. Thank you!

**Closed by matmkian** 2016-05-12 16:03 UTC
Labels: bug
