### ISSUE TITLE
Would be nice to be able to turn off the search in selects

### ISSUE THREAD

**Issue by erapoport** [lumapps/lumX#367] opened 2015-10-30 10:26 UTC
For short dropdowns with few options, having the search box is an overkill (especially since you can't go from search box to search options with just the keyboard down arrow).

Would be nice to be able to hide it via an attribute setting. I wanted to hide it with CSS, but it hangs off the body element with no way of distinguishing where it came from, so I can't style certain selects differently.

**Comment by AllSolutionsNL** [comment] 2015-11-05 14:53
this is a duplicate of issue #103   
There is also a branch with this enhancement ready, but it is waiting for something before it is merged in.

**Comment by matmkian** [comment] 2016-02-24 09:42
We've just released LumX v1.0.0rc1. This new version fixes the issue, so I'm closing it.

**Closed by matmkian** 2016-02-24 09:42 UTC
