### ISSUE TITLE
How to implement a sidenav?

### ISSUE THREAD

**Issue by digitalcraftsman** [lumapps/lumX#239] opened 2015-04-08 19:58 UTC
I would like to use the sidenav like the one on the project page. The documentation does not give any further information or examples about it.

**Comment by alannsiqueira** [comment] 2015-05-02 05:31
I would like to use the sidenav like the one on the project page. The documentation does not give any further information or examples about it. [2]

**Comment by ThomasCrvsr** [comment] 2015-05-11 09:06
This is a duplicate of https://github.com/lumapps/lumX/issues/38, as I did a sidenav on my current project I'll try to post an example today.

**Comment by ThomasCrvsr** [comment] 2015-05-11 18:13
I gave it a go here : https://github.com/ThomasCrvsr/lumx-sidebar-example (though it's a quick implementation and it could be improved)

**Comment by digitalcraftsman** [comment] 2015-05-11 19:14
Thanks for providing this example.

**Closed** 2015-05-13 13:29 UTC
