### ISSUE TITLE
Both FAB icons visible after click

### ISSUE THREAD

**Issue by cranst0n** [lumapps/lumX#97] opened 2015-01-05 16:56 UTC
After clicking a FAB, both of the icons are always visible, one on top of the other.

**Comment by malexandre** [comment] 2015-01-09 16:01
Hi!

I can't seem to reproduce the problem. What's your environment? Could you give us a screenshot please? When you say click, it's on the FAB itself or on of the little ones?

**Comment by cranst0n** [comment] 2015-01-09 18:28
Under Linux using Chrome 39.0.2171.95 (64-bit).

Here's the intial FAB:

![initial](https://cloud.githubusercontent.com/assets/1173143/5684893/2accfec4-9803-11e4-8f3b-99fa90bd673b.png)

Then when hovered (still no click):

![hovered](https://cloud.githubusercontent.com/assets/1173143/5684897/3356d7e0-9803-11e4-8ba9-1a58f9b198ec.png)

Finally after clicking and hovered:

![after-click](https://cloud.githubusercontent.com/assets/1173143/5684900/3e653a3c-9803-11e4-825a-036df68039ad.png)


A little tough to see but the plus icon is underneath the flag icon.

**Comment by malexandre** [comment] 2015-01-11 20:45
Thanks for the screenshots, perfect! The team will work on that.

**Comment by TeamChad** [comment] 2015-01-30 02:56
I have replicated this with the ripple applied. The ripple span gets attached as the first child invalidating the following css (the ripple span becomes the first child and gets scaled to 0 and the first icon does not) - 

.fab__primary .mdi {
            &:first-child {
                @include transform(scale(0));
            }

            &:last-child {
                @include transform(scale(1));
            }
        }

Also, having the fab menu activated on hover is ok for desktop but seems to be a 2 touch process on mobile when the ripple is applied.

**Comment by matmkian** [comment] 2015-02-20 18:18
It's now fixed, i close the issue.

**Closed by matmkian** 2015-02-20 18:18 UTC
Labels: bug
