### ISSUE TITLE
Text field valid state icon color

### ISSUE THREAD

**Issue by acatcalledanarchy** [lumapps/lumX#146] opened 2015-02-05 11:20 UTC
When a **lx-text-field** is focused the corresponding icon is highlighted in blue, similarly when the **lx-text-field** has an error state the icon is highlighted in red.

However when a **lx-text-field** has a valid state the icon is not highlighted in green.

**Comment by matmkian** [comment] 2015-02-09 07:15
Thanks for reporting the issue. We're going to work on it very soon!

**Comment by acatcalledanarchy** [comment] 2015-02-09 13:12
Cheers **@matmkian**, much appreciated. Keep up the good work!

**Comment by Teeweetep** [comment] 2015-02-19 15:33
Hello, the issue is now fixed : https://github.com/lumapps/lumX/commit/4aa91dd31276193ba34aee2843a545e9253190e8 . 

Thanks for reporting.

**Closed by Teeweetep** 2015-02-19 15:33 UTC
Labels: bug
