### ISSUE TITLE
dialog-filter not hidden, after opening multiple dialog

### ISSUE THREAD

**Issue by badoet** [lumapps/lumX#349] opened 2015-09-20 05:08 UTC
after opening multiple dialog at the same time, 
closing all the dialogs does not cause the dialog-filter to be hidden.
the dialog-filter just remain there.
is this behaviour not supported?
how can i achieve this behaviour?

**Comment by badoet** [comment] 2015-09-20 05:30
hmm realized that the LxDialogService created a .dialog-filter div every time it opens a new dialog id.
and the dialogFilter is a single variable that hold the current .dialog-filter element
and it doesnt link it to the dialog id. 

it would b nice to have the dialog-filter to link to the id through a hash table.

currently, i manually manage the opened dialog and when there is 0 dialog opened, i run `$( ".dialog-filter" ).remove();` 
hacky ugly solution :stuck_out_tongue:

**Comment by sijmenvos** [comment] 2016-02-20 20:24
I can confirm this problem, when you 'spam' one dialog it adds multiple .dialog-filter elements to the DOM and only removes one. Then an element gets left behind and the page seems to 'freeze' but it's because of the element.

**Comment by badoet** [comment] 2016-02-22 01:47
any plan to incorporate fix into the library itself?
or leave it to user to manage its own lumx dialog?

**Comment by matmkian** [comment] 2016-02-29 09:33
We've just released LumX v1.0.0rc1. This new version fixes the issue, so I'm closing it.

**Closed by matmkian** 2016-02-29 09:33 UTC

**Comment by FernandoFranco** [comment] 2016-03-30 19:40
Hi, sorry reopen this...
I'm using v1.0.0rc3 and this persist, and i solve this with:

in file: dist/lumx.js
in LxDialogService:

remove:
  var dialogFilter; (line ~985)

after, replace all resting dialogFilter to:
  scopeMap[_dialogId].dialogFilter
